# prometheus 配置文件
global:
    scrape_interval:     15s
    evaluation_interval: 15s
  
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: nats-monitor-varz
    static_configs: 
      - targets: ['integrated-monitor:4001', 'integrated-monitor:4002','integrated-monitor:4003']

  - job_name: nats-monitor-connz
    static_configs: 
      - targets: ['integrated-monitor:4011', 'integrated-monitor:4012','integrated-monitor:4013']

  - job_name: nats-monitor-routez
    static_configs: 
      - targets: ['integrated-monitor:4021', 'integrated-monitor:4022','integrated-monitor:4023']

  - job_name: nats-monitor-subz
    static_configs: 
      - targets: ['integrated-monitor:4031', 'integrated-monitor:4032','integrated-monitor:4033']

  - job_name: nats-streaming-serverz
    static_configs: 
      - targets: ['integrated-monitor:4041', 'integrated-monitor:4042','integrated-monitor:4043']

  - job_name: nats-streaming-channelz
    static_configs: 
      - targets: ['integrated-monitor:4051', 'integrated-monitor:4052','integrated-monitor:4053']

  - job_name: prometheus-nats-exporter-server
    static_configs: 
      - targets: ['integrated-monitor:9100']