version: '3.3'

networks: 
  rbmq-net:

services:

  rabbitmq1:
    image: rabbitmq:3.8-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    restart: on-failure
    networks: 
      - rbmq-net
    container_name: rabbitmq1

  rabbitmq2:
    image: rabbitmq:3.8-management
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    command: ["sh","/usr/local/bin/cluster-entrypoint.sh"]
    networks: 
      - rbmq-net
    container_name: rabbitmq2
    restart: on-failure

  rabbitmq3:
    image: rabbitmq:3.8-management
    hostname: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    command: ["sh","/usr/local/bin/cluster-entrypoint.sh"]
    restart: on-failure
    networks: 
      - rbmq-net
    container_name: rabbitmq3
    
  haproxy:
    image: haproxy:1.7
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 15672:15672
      - 5672:5672
    networks: 
      - rbmq-net
    restart: on-failure
